# Online Config Subscribe
# Clash For Android
# Credits [fyn170](https://github.com/fyn170/conf-cfa)
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: ""
secret: ""
bind-address: "*"
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
dns:
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.adguard.com/dns-query
  - https://dns-google.com/dns-query
  - tls://dns.adguard.com
  - tls://dns-google.com/
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
   - 8.8.8.8
   - 8.8.4.4
proxy-providers:
  Server:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/server.yaml"
    path: "./server.yaml"
    health-check:
      enable: true
      interval: 99
      url: http://www.gstatic.com/generate_204
    interval: "300"
proxy-groups:
- name: 18+
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: ADS
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
  - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
  - RULE-SET,18+,Server
  - RULE-SET,Ads,Ads
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Gaming,Server
  - RULE-SET,Reject,REJECT
  - RULE-SET,Sosmed,Server
  - RULE-SET,Stream,Server
  - MATCH,Server
  - GEOSITE,Ads
rule-providers:
  18+:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/ads.yaml"
    path: "./saru.yaml"
  Ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/ads.yaml"
    path: "./ads.yaml"
  Chat:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/direct.yaml"
    path: "./direct.yaml"
  Direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/direct.yaml"
    path: "./direct.yaml"
  Gaming:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/gaming.yaml"
    path: "./gaming.yaml"
  Reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/reject.yaml"
    path: "./reject.yaml"
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/sosmed.yaml"
    path: "./sosmed.yaml"
  Stream:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/stream.yaml"
    path: "./stream.yaml"
