# Online Config Subscribe
# Clash For Android
# Credits [fyn170](https://github.com/fyn170/conf-cfa)
---
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: ""
secret: ""
bind-address: "*"
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
profile:
  store-selected: true
  store-fake-ip: true
dns:
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 94.140.14.14
  - 94.140.15.15
  - https://dns.adguard-dns.com/dns-query
  - https://dns.google/dns-query
  - tls://dns.adguard-dns.com
  - tls://dns.google
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "+.*"
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 94.140.14.14
  - 94.140.15.15
proxy-providers:
  AXIS:
    type: http
    behavior: classical
    path: "./axis.yaml"
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/akun/axis.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  TSEL:
    type: http
    behavior: classical
    path: "./tsel.yaml"
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/akun/tsel.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  XL-1:
    type: http
    behavior: classical
    path: "./exel1.yaml"
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/akun/exel1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  XL-2:
    type: http
    behavior: classical
    path: "./exel2.yaml"
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/akun/exel2.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
proxy-groups:
- name: 18+
  type: select
  proxies:
  - REJECT
  - Server
- name: Ads
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  - Server
- name: AXIS🟣
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - AXIS
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
- name: TSEL🔴
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - TSEL
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
- name: XL-1🔵
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - XL-1
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
- name: XL-2🔵
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - XL-2
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
- name: Server
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - AXIS🟣
  - TSEL🔴
  - XL-1🔵
  - XL-2🔵
rules:
  - RULE-SET,18+,18+
  - RULE-SET,Ads,Ads
  - RULE-SET,Gaming,Server
  - RULE-SET,Olshop,Server
  - RULE-SET,Reject,REJECT
  - RULE-SET,Sosmed,Server
  - RULE-SET,Stream,Server
  - MATCH,Server
rule-providers:
  18+:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/saru.yaml"
    path: "./saru.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/ads.yaml"
    path: "./ads.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Gaming:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/gaming.yaml"
    path: "./gaming.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Olshop:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/olshop.yaml"
    path: "./olshop.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/reject.yaml"
    path: "./reject.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml"
    path: "./sosmed.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  Stream:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml"
    path: "./stream.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120