port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
proxy-providers:
  Server:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/server.yaml"
    path: "./server.yaml"
    health-check:
      enable: true
      interval: 99
      url: http://www.gstatic.com/generate_204
    interval: "300"
proxy-groups:
- name: ADS
  type: select
  proxies:
  - DIRECT
  - REJECT
- name: Chat
  type: select
  strategy: consistent-hashing
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - Server
- name: Server
  type: url-test
  strategy: consistent-hashing
  disable-udp: false
  use:
   - Server
  url: http://www.gstatic.com/generate_204
  interval: '300'
  
rules:
- RULE-SET,Ads,ADS
- RULE-SET,Direct,DIRECT
- RULE-SET,Gaming,Server
- RULE-SET,Reject,REJECT
- RULE-SET,Sosmed,Server
- RULE-SET,Stream,Server

rule-providers:
  Ads:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/ads.yaml"
    path: "./ads.yaml"
  Chat:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/direct.yaml"
    path: "./direct.yaml"
  Direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/direct.yaml"
    path: "./direct.yaml"
  Gaming:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/gaming.yaml"
    path: "./gaming.yaml"
  Reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/reject.yaml"
    path: "./reject.yaml"
  Sosmed:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/sosmed.yaml"
    path: "./sosmed.yaml"
  Stream:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/fyn170/conf-cfa/main/Provider%20files/stream.yaml"
    path: "./stream.yaml"
